# Generated by Django 4.0.4 on 2022-09-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='score',
        ),
        migrations.AddField(
            model_name='score1',
            name='team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
