# Generated by Django 4.0.4 on 2022-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_score1_team_score_delete_score_score1_team_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(unique=True),
        ),
    ]
